org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.java.home=/data/data/com.termux/files/usr/lib/jvm/java-21-openjdk
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.configureondemand=false

# COMPLETE HERMES DISABLE
hermesEnabled=false
EXPO_USE_HERMES=false
jsEngine=jsc
android.enableHermes=false
org.gradle.jvm.toolchain.install.auto=false
